name: Publish Package To Npm
on:
  push:
    branches:
      - master
  workflow_run:
    # 指定要依赖的工作流
    workflows: ["Basic Work Of PrePublish"]
    # 当且仅当依赖的工作流完成时才去触发
    types:
      - completed
jobs:
  publish:
    runs-on: ubuntu-latest